config/routes.rb
Rails.application.routes.draw do
  root to: 'drugs#index'

  get '/download' => 'downloads#index'

  namespace :api do
    namespace :v1 do
      get '/drugs' => 'drugs#index'
      get '/search' => 'drugs#search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drug.rb
class Drug < ApplicationRecord
end

app/models/drug_pdf.rb
require "render_anywhere"

class DrugPdf
  include RenderAnywhere

  def initialize(drugs)
    @drugs = drugs
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/drug.pdf")
    # using PDFKit to save the PDF file in the rails public folder
  end

  private

  attr_reader :drugs

  def as_html
    render template: "drugs/pdf", layout: "drugs_pdf", locals: { drugs: drugs }
    # layout refers to drugs_pdf.erb
  end
end

app/controllers/api/v1/drugs_controller.rb
class Api::V1::DrugsController < ApplicationController
  def index
    @drugs = Drug.all
    render 'index.json.jbuilder'
  end

  def search
    @drugs = []
    params[:search].each do |drug_name|
      @drugs << Drug.find_by(name: drug_name)
    end
    render 'search.json.jbuilder'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  # NEED TO UPDATE "DRUG.ALL TO DRUGS CHOSEN" - maybe add table in database called "searches" and another joining table linking drugs to particular search_id
  def index
    respond_to do |format|
      format.pdf {
        send_file DrugPdf.new(Drug.all).to_pdf,
          filename: "data_download",
          type: "application/pdf",
          disposition: "inline" # can also do "attachment" for download
      }
    end
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def index
    @drugs = Drug.all
    render 'index.html.erb'
  end
end

app/helpers/api/v1/drugs_helper.rb
module Api::V1::DrugsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/index.html.erb
<div class="margin">
  <div id="app">
    <div class="row">
      <div class="col-md-6">
        <div id="searchError"></div>
        <v-select multiple v-model="drugSearch" :options="options" placeholder="Search drugs ..." ></v-select>
      </div>
      <div class="col-md-6">
        <button v-on:click="search($event)" class="btn btn-sm btn-primary" type="submit" > Search</button>
        <button v-on:click="reset()" class="btn btn-sm btn-danger" type="submit" > Reset</button>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 white-space">
        <table v-if="searchComplete" class="table table-bordered table-striped">
          <col width="20px">
          <col width="30px">
          <thead>
            <tr>
              <th>Name</th>
              <th>Side Effects</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="drug in Drugs">
              <td>{{ drug.name }}</td>
              <td>{{ drug.effects }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6" v-if="searchComplete">
        <%= link_to "Download PDF", download_path(@drugs, format: "pdf") %>
      </div>
    </div>
  </div>
</div>

app/views/drugs/pdf.html.erb
<div class="margin">
  <div id="app">
    <div class="row">
      <div class="col-md-6 white-space">
        <table class="table table-bordered table-striped">
          <col width="20px">
          <col width="30px">
          <thead>
            <tr>
              <th>Name</th>
              <th>Side Effects</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="drug in Drugs">
              <td>{{ drug.name }}</td>
              <td>{{ drug.effects }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wylie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/drugs_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>[INSERT TITLE]</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>